name: edu_app_project
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  audioplayers: ^6.1.0
  awesome_snackbar_content: ^0.1.4
  app_links: ^6.3.0
  badges: ^3.1.2
  bloc: ^8.1.4
  carousel_slider: ^5.0.0
  chewie: ^1.8.5
  cloud_firestore: ^5.4.4
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.5
  ffmpeg_kit_flutter_new: ^3.2.0
  file_icon: ^1.0.0
  file_picker: ^8.1.3
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.4
  firebase_ui_firestore: ^1.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_chat_types: ^3.6.2
  flutter_dotenv: ^5.2.1
  flutter_link_previewer: ^3.2.2
  flutter_stripe: ^11.3.0
  flutter_svg: ^2.0.9
  flutter_tindercard:
    git:
      url: https://github.com/NonymousMorlock/flutter_tindercard.git
  gradient_icon: ^2.0.9
  font_awesome_flutter: ^10.7.0
  get_it: ^8.0.0
  http: ^0.13.6
  iconly: ^1.0.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  lottie: ^3.0.0
  open_file: ^3.5.9
  path_provider: ^2.1.4
  photo_view: ^0.14.0
  provider: ^6.1.2
  purchases_flutter: ^8.2.1
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.0+3
  step_progress_indicator: ^1.0.2
  swipe_to: ^1.0.6
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  webview_flutter: ^4.10.0
  youtube_metadata: ^1.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/vectors/logo2.png"

dev_dependencies:
  bloc_test: ^9.1.7
  fake_cloud_firestore: ^3.0.3
  firebase_auth_mocks: ^0.14.1
  firebase_storage_mocks: ^0.7.0
  flutter_test:
    sdk: flutter
  google_sign_in_mocks: ^0.3.0
  mocktail: ^1.0.4
  very_good_analysis: ^5.0.0+1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/lotties/
    - assets/sounds/
    - assets/.env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter_28pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter_28pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter_28pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter_28pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter_28pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter_28pt-Black.ttf
          weight: 900
        - asset: assets/fonts/inter/Inter_28pt-Italic.ttf
          style: italic

    - family: Merriweather
      fonts:
        - asset: assets/fonts/merriweather/Merriweather-Regular.ttf
          weight: 400
        - asset: assets/fonts/merriweather/Merriweather-Light.ttf
          weight: 300
        - asset: assets/fonts/merriweather/Merriweather-Bold.ttf
          weight: 700
        - asset: assets/fonts/merriweather/Merriweather-Black.ttf
          weight: 900
        - asset: assets/fonts/merriweather/Merriweather-Italic.ttf
          style: italic
